#!/usr/bin/env python3
"""Print the little-workshop policies attached to a project: name, gate points, rule.

Generated by little-workshop (registry/claude_templates.py): change the generator, not this copy."""

import argparse
import json
import os
import subprocess
import sys


def lws(*args):
    env = {**os.environ, "LWS_NO_PROGRESS": "1"}
    result = subprocess.run(["lws", *args], capture_output=True, text=True, env=env)
    try:
        return json.loads(result.stdout)
    except ValueError:
        sys.exit("could not read little-workshop's answer to `lws " + " ".join(args) + "`: is the daemon running "
                 "(`lws core status`)?")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--project-id", required=True)
    parser.add_argument("--gate", default=None, help="Only the policies gating this action (commit, branch_finish, ...)")
    args = parser.parse_args()
    attached = {row["policy_id"]: row for row in lws("policy", "projects", "list", "--project-id", args.project_id).get("projects", [])}
    shown = 0
    for policy in sorted(lws("policy", "list").get("policies", []), key=lambda p: p.get("topic") or ""):
        if policy.get("id") not in attached:
            continue
        gates = policy.get("gating") or policy.get("gate_points") or []
        if args.gate and args.gate not in gates:
            continue
        held = "" if attached[policy["id"]].get("gating_enabled", True) else " (gating off for this project)"
        print("- " + str(policy.get("topic")) + " [" + (", ".join(gates) or "advisory") + "]" + held + ": " + " ".join(str(policy.get("ears_text") or "").split()))
        shown += 1
    print(str(shown) + " polic" + ("y" if shown == 1 else "ies") + " for " + args.project_id + (" gating " + args.gate if args.gate else ""))


if __name__ == "__main__":
    main()
