#!/usr/bin/env python3
"""PreToolUse hook: keep this project's Claude sessions inside this project.

Registered in .claude/settings.json for Bash and the little-workshop MCP tools.
Usage: lws_scope_guard.py PROJECT_ID, with the hook's JSON on stdin.

Denies an `lws` command or a little-workshop MCP call that names another project
(--project-id, project_id, a project name), or that leaves the project id out
where leaving it out acts on every project. Input it cannot read passes: the
permission rules in settings.json are the other gate. Generated by little-workshop
(registry/claude_templates.py): change the generator, not this copy."""

import json
import re
import shlex
import sys

PREFIX = "mcp__little-workshop__"
# MCP tools whose project_id is optional: left out, they act on every project.
NEEDS_PROJECT_ID = frozenset((
    "workshop_build_package_list",
    "workshop_build_run_list",
    "workshop_policy_projects_list",
    "workshop_policy_results",
    "workshop_requirements_list",
    "workshop_requirements_suite_list",
    "workshop_schedule_add",
))
# MCP tools that take the project's own name in `name`.
NAMED_PROJECT = frozenset((
    "workshop_project_bootstrap",
    "workshop_project_connect_github",
    "workshop_project_get",
    "workshop_project_import",
    "workshop_project_remove",
))
# `lws project <command>`: these create or register another project.
FOREIGN_PROJECT_COMMANDS = ("bootstrap", "import")
# `lws project <command> NAME`: these act on the project NAME.
NAMED_PROJECT_COMMANDS = ("connect-github", "remove")
SHELLS = ("bash", "sh", "zsh", "dash")
OPERATORS = set("();<>|&`")
HEREDOC = re.compile(r"(?<!<)<<-?\s*(['\"]?)([A-Za-z_]\w*)\1")


def without_heredoc_bodies(command):
    """The command line minus the text of its here-documents: that is data, not commands."""
    kept, delimiters = [], []
    for line in command.split("\n"):
        if delimiters:
            if line.strip() == delimiters[0]:
                delimiters.pop(0)
            continue
        kept.append(line)
        delimiters.extend(match.group(2) for match in HEREDOC.finditer(line))
    return "\n".join(kept)


def simple_commands(command):
    """The command line split into simple commands (lists of words)."""
    command = without_heredoc_bodies(command)
    try:
        lexer = shlex.shlex(command.replace("\n", " ; "), posix=True, punctuation_chars="".join(sorted(OPERATORS)))
        lexer.whitespace_split = True
        words = list(lexer)
    except ValueError:
        return []
    commands, current = [], []
    for word in words:
        if set(word) <= OPERATORS:
            if current:
                commands.append(current)
            current = []
        else:
            current.append(word)
    if current:
        commands.append(current)
    return commands


def lws_violation(args, own):
    """Why these `lws` arguments leave the project, or None."""
    for i, arg in enumerate(args):
        option, equals, value = arg.partition("=")
        if len(option) >= 4 and ("--project-id".startswith(option) or option.startswith("--project")):
            if not equals:
                value = args[i + 1] if i + 1 < len(args) else None
            if value is not None and value != own:
                return f"names project {value!r}"
    if args[:1] == ["project"] and len(args) > 1:
        if args[1] in FOREIGN_PROJECT_COMMANDS:
            return f"`lws project {args[1]}` registers another project"
        if args[1] in NAMED_PROJECT_COMMANDS and len(args) > 2 and not args[2].startswith("-") and args[2] != own:
            return f"names project {args[2]!r}"
    return None


def bash_violation(command, own):
    for words in simple_commands(command):
        for i, word in enumerate(words):
            base = word.rsplit("/", 1)[-1]
            if base == "lws":
                problem = lws_violation(words[i + 1:], own)
                if problem:
                    return f"the lws command {problem}"
                break
            if base in SHELLS:
                for j, option in enumerate(words[i + 1:], i + 1):
                    if option.startswith("-") and not option.startswith("--") and "c" in option[1:]:
                        if j + 1 < len(words):
                            problem = bash_violation(words[j + 1], own)
                            if problem:
                                return problem
                        break
                break
    return None


def mcp_violation(tool, args, own):
    name = tool[len(PREFIX):]
    project = args.get("project_id")
    if project is not None and project != own:
        return f"{name} names project {project!r}"
    if project is None and name in NEEDS_PROJECT_ID:
        return f"{name} without project_id acts on every project"
    if name in NAMED_PROJECT and args.get("name") != own:
        return f"{name} names project {args.get('name')!r}"
    for entry in args.get("projects") or ():
        other = entry.get("project_id") if isinstance(entry, dict) else None
        if other is not None and other != own:
            return f"{name} names project {other!r}"
    return None


def main():
    own = sys.argv[1] if len(sys.argv) > 1 else ""
    try:
        event = json.load(sys.stdin)
        tool = event["tool_name"]
        args = event.get("tool_input") or {}
    except (ValueError, KeyError, TypeError):
        return
    if not own:
        return
    if tool.startswith(PREFIX):
        problem = mcp_violation(tool, args, own)
    elif tool == "Bash":
        problem = bash_violation(str(args.get("command", "")), own)
    else:
        return
    if problem:
        print(json.dumps({"hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": (
                f"little-workshop scope: this checkout is project {own!r} but {problem}. "
                "Work on other projects belongs in a session started from the little-projects root."
            ),
        }}))


if __name__ == "__main__":
    main()
