#!/usr/bin/env python3
"""PreToolUse hook: the hard layer of this project's Claude instructions.

Registered in .claude/settings.json for Bash, the file-edit tools and the
little-workshop MCP tools. Usage: lws_scope_guard.py PROJECT_ID, with the hook's
JSON on stdin. It refuses, and says what to do instead:
- an `lws` command or a little-workshop MCP call that names another project
  (--project-id, project_id, a project name), or that leaves the project id out
  where leaving it out acts on every project;
- a raw command that would bypass the policy gates little-workshop runs (git
  merge, tag, push, cherry-pick, branch deletion, --no-verify, a core.hooksPath
  override, systemd, twine, gh...), in any spelling it can parse;
- an edit of a file little-workshop generates (VERSION, .githooks, its .claude/
  files) or of a CLAUDE.md, which would stop Claude Code reading AGENTS.md.
Input it cannot read passes: the permission rules in settings.json and the
policies are the other gates. Generated by little-workshop
(registry/claude_templates.py): change the generator, not this copy."""

import json
import os
import re
import shlex
import sys

PREFIX = "mcp__little-workshop__"
# MCP tools whose project_id is optional: left out, they act on every project.
NEEDS_PROJECT_ID = frozenset((
    "workshop_build_package_list",
    "workshop_build_run_list",
    "workshop_policy_projects_list",
    "workshop_policy_results",
    "workshop_requirements_list",
    "workshop_requirements_suite_list",
    "workshop_schedule_add",
))
# MCP tools that take the project's own name in `name`.
NAMED_PROJECT = frozenset((
    "workshop_project_bootstrap",
    "workshop_project_connect_github",
    "workshop_project_get",
    "workshop_project_import",
    "workshop_project_remove",
))
# `lws project <command>`: these create or register another project.
FOREIGN_PROJECT_COMMANDS = ("bootstrap", "import")
# `lws project <command> NAME`: these act on the project NAME.
NAMED_PROJECT_COMMANDS = ("connect-github", "remove")
# Why a raw command is refused, and the route to take instead.
ROUTES = {
    "branch-delete": "workshop_version_<type>_finish deletes a finished branch",
    "cherry-pick": "a fix reaches the integration branch through workshop_version_hotfix_start / _finish (hotfix-propagates-by-merge)",
    "destructive": "it discards work that may not be yours: ask the user what to remove",
    "github": "workshop_project_connect_github creates the repository, little-workshop's agent flow opens and merges pull requests, and a release comes from workshop_version_release_finish",
    "hooks-path": "core.hooksPath stays .githooks, where the VERSION sync and the commit-gated policies run",
    "install": "the project installs with `bazel run //:install`; a server is deployed with workshop_deployment_deploy",
    "merge": "a branch is finished with workshop_version_<type>_finish, which runs the branch_finish policies and merges with --no-ff",
    "no-verify": "the commit hooks write VERSION and run the commit-gated policies: fix what the hook reports and commit again",
    "publish": "packages are published with workshop_build_publish_pypi / _vsix (wheel-filename-has-version runs there)",
    "push": "little-workshop pushes when it finishes or releases, and workshop_project_connect_github creates the remote; a push the user asks for is theirs to run",
    "systemd": "servers run through workshop_deployment_deploy / _stop / _status",
    "tag": "tags are written by workshop_version_release_* (annotated v<M>.<m>.<p>); read the release state with workshop_version_status"
}
# Files little-workshop writes, relative to the checkout -> how they change.
GENERATED = {
    ".claude/hooks/lws_scope_guard.py": "little-workshop generates it: change src/registry/claude_templates.py in little-workshop and run its `python3 tools/sync_claude_files.py --write`",
    ".claude/little-workshop.md": "little-workshop generates it: change src/registry/claude_templates.py in little-workshop and run its `python3 tools/sync_claude_files.py --write`",
    ".claude/rules/claude-instructions.md": "little-workshop generates it: change src/registry/claude_templates.py in little-workshop and run its `python3 tools/sync_claude_files.py --write`",
    ".claude/skills/policy-preflight/SKILL.md": "little-workshop generates it: change src/registry/claude_templates.py in little-workshop and run its `python3 tools/sync_claude_files.py --write`",
    ".claude/skills/policy-preflight/scripts/preflight.py": "little-workshop generates it: change src/registry/claude_templates.py in little-workshop and run its `python3 tools/sync_claude_files.py --write`",
    ".claude/skills/workshop-lifecycle/SKILL.md": "little-workshop generates it: change src/registry/claude_templates.py in little-workshop and run its `python3 tools/sync_claude_files.py --write`",
    "VERSION": "little-workshop writes VERSION: the pre-commit hook on feature/ and improvement/ branches (`lws version sync-version-files`), the finish and release commands elsewhere"
}
GIT_HOOKS = ('.githooks/pre-commit', '.githooks/commit-msg')
EDIT_TOOLS = ('Edit', 'Write', 'MultiEdit', 'NotebookEdit')
STRAY_INSTRUCTIONS = ("CLAUDE.md", "CLAUDE.local.md")
SHELLS = ("bash", "sh", "zsh", "dash")
OPERATORS = set("();<>|&`")
HEREDOC = re.compile(r"(?<!<)<<-?\s*(['\"]?)([A-Za-z_]\w*)\1")
# git's global options that take a value as the next word.
GIT_VALUE_OPTIONS = ("-C", "-c", "--git-dir", "--work-tree", "--namespace", "--exec-path", "--config-env",
                     "--super-prefix")
# `git commit` options whose value is the next word (so that word is never read as a flag).
COMMIT_VALUE_OPTIONS = ("-m", "-F", "-C", "-c", "-t", "--message", "--file", "--author", "--date", "--template",
                        "--reuse-message", "--reedit-message", "--fixup", "--squash", "--trailer", "--cleanup",
                        "--pathspec-from-file")
COMMIT_VALUE_LETTERS = "mFCct"


def without_heredoc_bodies(command):
    """The command line minus the text of its here-documents: that is data, not commands."""
    kept, delimiters = [], []
    for line in command.split("\n"):
        if delimiters:
            if line.strip() == delimiters[0]:
                delimiters.pop(0)
            continue
        kept.append(line)
        delimiters.extend(match.group(2) for match in HEREDOC.finditer(line))
    return "\n".join(kept)


def simple_commands(command):
    """The command line split into simple commands (lists of words)."""
    command = without_heredoc_bodies(command)
    try:
        lexer = shlex.shlex(command.replace("\n", " ; "), posix=True, punctuation_chars="".join(sorted(OPERATORS)))
        lexer.whitespace_split = True
        words = list(lexer)
    except ValueError:
        return []
    commands, current = [], []
    for word in words:
        if set(word) <= OPERATORS:
            if current:
                commands.append(current)
            current = []
        else:
            current.append(word)
    if current:
        commands.append(current)
    return commands


def lws_violation(args, own):
    """Why these `lws` arguments leave the project, or None."""
    for i, arg in enumerate(args):
        option, equals, value = arg.partition("=")
        if len(option) >= 4 and ("--project-id".startswith(option) or option.startswith("--project")):
            if not equals:
                value = args[i + 1] if i + 1 < len(args) else None
            if value is not None and value != own:
                return f"names project {value!r}"
    if args[:1] == ["project"] and len(args) > 1:
        if args[1] in FOREIGN_PROJECT_COMMANDS:
            return f"`lws project {args[1]}` registers another project"
        if args[1] in NAMED_PROJECT_COMMANDS and len(args) > 2 and not args[2].startswith("-") and args[2] != own:
            return f"names project {args[2]!r}"
    return None


def short_flags(word):
    """The letters of a short-option cluster (`-am` -> "am"), or "" for anything else."""
    return word[1:] if word.startswith("-") and not word.startswith("--") and len(word) > 1 else ""


def commit_skips_hooks(args):
    """Whether `git commit ARGS` turns the hooks off (--no-verify, or -n in a short-option cluster)."""
    skip_next = False
    for word in args:
        if skip_next:
            skip_next = False
            continue
        if word == "--":
            return False
        if word == "--no-verify":
            return True
        if word in COMMIT_VALUE_OPTIONS:
            skip_next = True
            continue
        for i, letter in enumerate(short_flags(word)):
            if letter == "n":
                return True
            if letter in COMMIT_VALUE_LETTERS:
                skip_next = i == len(word) - 2  # the value is the next word only when the letter ends the cluster
                break
    return False


def git_route(args):
    """The ROUTES key for `git ARGS` when it bypasses little-workshop, or None."""
    i, overrides = 0, []
    while i < len(args) and args[i].startswith("-"):
        option = args[i].split("=", 1)[0]
        if option in GIT_VALUE_OPTIONS and "=" not in args[i]:
            if option == "-c" and i + 1 < len(args):
                overrides.append(args[i + 1])
            i += 2
            continue
        i += 1
    if any(o.split("=", 1)[0].lower() == "core.hookspath" for o in overrides):
        return "hooks-path"
    if i >= len(args):
        return None
    sub, rest = args[i], args[i + 1:]
    if sub in ("merge", "cherry-pick", "tag", "push"):
        return sub
    if sub == "commit":
        return "no-verify" if commit_skips_hooks(rest) else None
    if sub == "branch":
        deleting = any(w in ("--delete", "-d", "-D") or set(short_flags(w)) & {"d", "D"} for w in rest)
        return "branch-delete" if deleting else None
    if sub == "reset":
        return "destructive" if "--hard" in rest else None
    if sub == "clean":
        return "destructive"
    if sub == "config" and any(w.lower() == "core.hookspath" for w in rest):
        values = [w for w in rest if not w.startswith("-") and w.lower() != "core.hookspath"]
        unsetting = any(w in ("--unset", "--unset-all") for w in rest)
        return "hooks-path" if unsetting or (values and values != [".githooks"]) else None
    return None


def command_route(words):
    """The ROUTES key for one simple command, or None."""
    base = words[0].rsplit("/", 1)[-1]
    args = words[1:]
    if base == "git":
        return git_route(args)
    if base == "systemd-run":
        return "systemd"
    if base == "systemctl" and "--user" in args and set(args) & {"start", "stop", "restart", "kill"}:
        return "systemd"
    if base == "twine":
        return "publish"
    if base == "pipx" and args[:1] == ["install"]:
        return "install"
    if base == "gh" and (args[:2] in (["repo", "create"], ["pr", "create"], ["pr", "merge"]) or args[:1] == ["release"]):
        return "github"
    return None


def without_env_assignments(words):
    """The words after any leading NAME=value assignments and `env`, `command`, `exec`, `sudo`."""
    i = 0
    while i < len(words) and (re.match(r"^[A-Za-z_]\w*=", words[i]) or words[i] in ("env", "command", "exec", "sudo")):
        i += 1
    return words[i:]


def bash_violation(command, own):
    for words in simple_commands(command):
        words = without_env_assignments(words)
        if not words:
            continue
        route = command_route(words)
        if route:
            shown = " ".join(words[:3])
            return f"`{shown}` is refused here: {ROUTES[route]}."
        for i, word in enumerate(words):
            base = word.rsplit("/", 1)[-1]
            if base == "lws":
                problem = lws_violation(words[i + 1:], own)
                if problem:
                    return (f"this checkout is project {own!r} but the lws command {problem}. Work on other "
                            "projects belongs in a session started from the little-projects root.")
                break
            if base in SHELLS:
                for j, option in enumerate(words[i + 1:], i + 1):
                    if option.startswith("-") and not option.startswith("--") and "c" in option[1:]:
                        if j + 1 < len(words):
                            problem = bash_violation(words[j + 1], own)
                            if problem:
                                return problem
                        break
                break
    return None


def mcp_violation(tool, args, own):
    name = tool[len(PREFIX):]
    project = args.get("project_id")
    if project is not None and project != own:
        return f"{name} names project {project!r}"
    if project is None and name in NEEDS_PROJECT_ID:
        return f"{name} without project_id acts on every project"
    if name in NAMED_PROJECT and args.get("name") != own:
        return f"{name} names project {args.get('name')!r}"
    for entry in args.get("projects") or ():
        other = entry.get("project_id") if isinstance(entry, dict) else None
        if other is not None and other != own:
            return f"{name} names project {other!r}"
    return None


def edit_violation(args, root, own):
    """Why editing this file is refused, or None. Paths outside the checkout pass."""
    path = args.get("file_path") or args.get("notebook_path")
    if not isinstance(path, str) or not path or not root:
        return None
    full = os.path.realpath(path if os.path.isabs(path) else os.path.join(root, path))
    rel = os.path.relpath(full, os.path.realpath(root)).replace(os.sep, "/")
    if rel == ".." or rel.startswith("../"):
        return None
    if rel.rsplit("/", 1)[-1] in STRAY_INSTRUCTIONS or rel == ".claude/CLAUDE.md":
        return (f"{rel} is refused here: Claude Code reads AGENTS.md only where no CLAUDE.md, .claude/CLAUDE.md or "
                "CLAUDE.local.md exists. Put project guidance in .claude/AGENTS.md or a path-scoped "
                ".claude/rules/ file, and personal notes in ~/.claude/.")
    if rel in GENERATED:
        return f"{rel} is refused here: {GENERATED[rel]}."
    if rel in GIT_HOOKS:
        return (f"{rel} is refused here: `lws version install-hooks --project-id {own}` writes it (generator: "
                "little-workshop's src/version/commands/sync_version_files.py).")
    return None


def main():
    own = sys.argv[1] if len(sys.argv) > 1 else ""
    try:
        event = json.load(sys.stdin)
        tool = event["tool_name"]
        args = event.get("tool_input") or {}
    except (ValueError, KeyError, TypeError):
        return
    if not own or not isinstance(args, dict):
        return
    if tool.startswith(PREFIX):
        problem = mcp_violation(tool, args, own)
        if problem:
            problem = (f"this checkout is project {own!r} but {problem}. Work on other projects belongs in a "
                       "session started from the little-projects root.")
    elif tool == "Bash":
        problem = bash_violation(str(args.get("command", "")), own)
    elif tool in EDIT_TOOLS:
        problem = edit_violation(args, os.environ.get("CLAUDE_PROJECT_DIR") or event.get("cwd"), own)
    else:
        return
    if problem:
        print(json.dumps({"hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": f"little-workshop: {problem}",
        }}))


if __name__ == "__main__":
    main()
