#!/usr/bin/env python3
"""PreToolUse hook and output filter for test runs.

As a hook (no arguments, the hook's JSON on stdin): when the Bash command is one plain test run
(pytest, bazel test, npm test, vitest, tools/run-unity-tests) it rewrites the command to pipe its
output through this file with --filter, keeping the command's exit status. Anything else passes
unchanged, as does input it cannot read.

As a filter (--filter): short output is printed whole. Long output is saved to a file and reduced
to the lines that report failures, with some context, and the end of the run.

Generated by little-workshop (registry/claude_templates.py): change the generator, not this copy."""

import json
import os
import re
import sys
import tempfile

TEST_COMMAND = re.compile(r"^\s*(python3? -m pytest|pytest|bazel test|npm (run )?test|npx vitest|tools/run-unity-tests)\b")
SHELL_SYNTAX = re.compile(r"[|;&<>`$()]")
KEEP_WHOLE_LINES = 150
TAIL_LINES = 40
CONTEXT_LINES = 3
MAX_KEPT_LINES = 400
FAILURE = re.compile(r"(FAIL|ERROR|Error|error:|Traceback|AssertionError|^E\s|^\s*assert |panicked|✗|✘|not ok)")


def hook():
    try:
        event = json.load(sys.stdin)
        command = event["tool_input"]["command"]
    except (ValueError, KeyError, TypeError):
        return
    if event.get("tool_name") != "Bash" or not TEST_COMMAND.match(command) or SHELL_SYNTAX.search(command):
        return
    here = os.path.join(os.environ.get("CLAUDE_PROJECT_DIR") or ".", ".claude", "hooks", "test_output_filter.py")
    rewritten = "set -o pipefail; " + command + " 2>&1 | python3 " + json.dumps(here) + " --filter"
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse", "permissionDecision": "allow",
        "permissionDecisionReason": "a test run, its output filtered to failures and the summary",
        "updatedInput": {**event["tool_input"], "command": rewritten},
    }}))


def filtered(lines):
    """The lines worth reading of a long test run, in order, with a marker where lines were left out."""
    keep = set(range(max(len(lines) - TAIL_LINES, 0), len(lines)))
    for index, line in enumerate(lines):
        if FAILURE.search(line):
            keep.update(range(max(index - CONTEXT_LINES, 0), min(index + CONTEXT_LINES + 1, len(lines))))
    chosen = sorted(keep)
    if len(chosen) > MAX_KEPT_LINES:
        chosen = chosen[:MAX_KEPT_LINES - TAIL_LINES] + chosen[-TAIL_LINES:]
    out, previous = [], -1
    for index in chosen:
        if index != previous + 1:
            out.append("[... " + str(index - previous - 1) + " line(s) left out ...]")
        out.append(lines[index])
        previous = index
    return out


def filter_output():
    lines = sys.stdin.read().splitlines()
    if len(lines) <= KEEP_WHOLE_LINES:
        print("\n".join(lines))
        return
    with tempfile.NamedTemporaryFile("w", prefix="test-output-", suffix=".log", delete=False, encoding="utf-8") as full:
        full.write("\n".join(lines) + "\n")
    print("[test output: " + str(len(lines)) + " lines, filtered to failures and the end of the run; all of it is in " + full.name + "]")
    print("\n".join(filtered(lines)))


if __name__ == "__main__":
    filter_output() if sys.argv[1:] == ["--filter"] else hook()
