[pytest]
pythonpath = src
addopts = --cov=src/little_meals --cov-report=term-missing --cov-fail-under=85 -p no:little_requirements -p little_requirements.tracing.pytest_plugin
testpaths = tests
norecursedirs = bazel-* .git .venv venv
markers =
    requirement(requirement_id): maps test case to a little-requirements requirement ID
