load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "unit_tests",
    srcs = ["_pytest_main.py", "conftest.py"] + glob(["test_*.py"]),
    main = "_pytest_main.py",
    deps = [
        "//src/little_meals:lib",
        "@pip//pytest",
        "@pip//pytest_cov",
        "@pip//coverage",
        "@pip//fastapi",
        "@pip//httpx",
        "@pip//jinja2",
        "@pip//pyyaml",
        "@pip//pydantic",
        "@pip//uvicorn",
        "@pip//apscheduler",
    ],
    data = [
        "//src/little_meals:package_data",
    ],
    python_version = "PY3",
    visibility = ["//visibility:public"],
)
