#!/usr/bin/env python3
"""Run the little-workshop policies that would gate an action on this project, against this
checkout, and print every failure with its reason. The `policy-preflight` skill's script.

    python3 .claude/skills/policy-preflight/scripts/preflight.py [--gate-point branch_finish]

Evaluates in little-workshop's policy sandbox (`lws policy evaluate`: the checks the gate itself
runs, nothing recorded or held). When the installed lws or the running Policy pillar predates
that, it runs the same policy scripts here, outside the sandbox, and says so.
Exit 0: nothing blocks. 1: a gating policy fails. 2: the policies could not be evaluated.
Generated by little-workshop (registry/claude_templates.py): change the generator, not this copy."""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

GATE_POINTS = ("branch_finish", "release", "package_publish", "build_install", "server_launch",
               "deploy_redeploy", "server_stop", "project_removal")
_SUMMARY = re.compile(r"(\d+) (failed|passed|skipped)")
# Terminal colour codes: a coloured `E   ...` line would hide the assertion message from the report.
_ANSI = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]")


def checkout_root():
    top = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True)
    return Path(top.stdout.strip()) if top.returncode == 0 and top.stdout.strip() else Path.cwd()


def project_id(root):
    """The project's little-workshop id: the scope guard's argument in .claude/settings.json,
    else the checkout's directory name (the ids are directory names)."""
    try:
        settings = json.loads((root / ".claude" / "settings.json").read_text(encoding="utf-8"))
        for entry in (settings.get("hooks") or {}).get("PreToolUse") or []:
            for hook in entry.get("hooks") or []:
                match = re.search(r"lws_scope_guard\.py\s+(\S+)", hook.get("command", ""))
                if match:
                    return match.group(1)
    except (OSError, ValueError):
        pass
    return root.name


def evaluate_in_sandbox(project, gate_point, root):
    """(result, None), or (None, why it could not run here) -- None reason means: fall back."""
    try:
        run = subprocess.run(
            ["lws", "policy", "evaluate", "--project-id", project, "--gate-point", gate_point,
             "--checkout", str(root), "--json"],
            capture_output=True, text=True,
        )
    except FileNotFoundError:
        return None, "lws is not installed"
    if run.returncode in (0, 1) and run.stdout.strip():
        return json.loads(run.stdout), None
    error = (run.stderr or run.stdout).strip()
    if "invalid choice" in error or "predates policy evaluate" in error:
        return None, None  # an lws or a Policy pillar from before `policy evaluate`
    return None, error or f"lws policy evaluate exited {run.returncode}"


def evaluate_locally(project, gate_point, root):
    """The same policies, fetched from little-workshop, run here with pytest outside the sandbox."""
    listed = subprocess.run(
        ["lws", "policy", "gating-for-job", "--project-id", project, "--categories", gate_point],
        capture_output=True, text=True,
    )
    if listed.returncode != 0:
        raise RuntimeError((listed.stderr or listed.stdout).strip() or "lws policy gating-for-job failed")
    results = []
    env = {**os.environ, "POLICY_PROJECT_DIR": str(root), "COLUMNS": "300", "PYTHONDONTWRITEBYTECODE": "1"}
    with tempfile.TemporaryDirectory(prefix="policy-preflight-") as scratch:
        for policy in json.loads(listed.stdout).get("policies", []):
            script = Path(scratch) / "test_policy.py"
            script.write_text(policy["test_script"], encoding="utf-8")
            run = subprocess.run(
                [sys.executable, "-m", "pytest", str(script), "-q", "-rA", "--tb=short", "--no-header",
                 "-p", "no:cacheprovider", "--color=no"],
                capture_output=True, text=True, env=env, cwd=scratch,
            )
            stdout = _ANSI.sub("", run.stdout)
            counts = {kind: int(n) for n, kind in _SUMMARY.findall(stdout.strip().splitlines()[-1] if stdout.strip() else "")}
            outcome = ("fail" if counts.get("failed") or run.returncode not in (0, 1) else
                       "pass" if counts.get("passed") else "not_applicable" if counts.get("skipped") else "error")
            reasons = [line[2:].strip() if line.startswith("E ") else line.strip()
                       for line in stdout.splitlines() if line.startswith(("E ", "SKIPPED "))]
            results.append({"topic": policy["topic"], "ears_text": policy["ears_text"], "gating": policy.get("gating", True),
                            "outcome": outcome, "detail": "\n".join(dict.fromkeys(reasons)) or stdout[-800:]})
    return {
        "project_id": project, "gate_point": gate_point, "results": results, "local": True,
        "blocking": [r["topic"] for r in results if r["outcome"] == "fail" and r["gating"]],
        "errors": [r["topic"] for r in results if r["outcome"] == "error"],
    }


def report(result):
    counts = {}
    for entry in result["results"]:
        counts[entry["outcome"]] = counts.get(entry["outcome"], 0) + 1
    labels = (("fail", "failed"), ("error", "could not run"), ("pass", "passed"), ("not_applicable", "not applicable"))
    summary = ", ".join(f"{counts[k]} {label}" for k, label in labels if counts.get(k)) or "no policy gates it"
    where = " (run here, outside the sandbox)" if result.get("local") else ""
    lines = [f"Policies gating {result['gate_point']} for {result['project_id']}{where}: {summary}"]
    for entry in result["results"]:
        if entry["outcome"] in ("fail", "error"):
            gating = "" if entry.get("gating", True) else " (gating off here: reported, never blocks)"
            lines.append(f"\n{'FAIL' if entry['outcome'] == 'fail' else 'ERROR'} {entry['topic']}{gating}")
            lines.append(f"  rule: {entry.get('ears_text', '')}")
            lines.extend(f"  {line}" for line in str(entry.get("detail", "")).splitlines())
    if result.get("blocking"):
        lines.append(f"\nWould hold the action: {', '.join(result['blocking'])}.")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Run the policies that would gate an action, against this checkout.")
    parser.add_argument("--gate-point", default="branch_finish", choices=GATE_POINTS)
    parser.add_argument("--project-id", default=None, help="Default: read from the checkout")
    parser.add_argument("--local", action="store_true", help="Run the policy scripts here instead of in the sandbox")
    args = parser.parse_args(argv)
    root = checkout_root()
    project = args.project_id or project_id(root)

    result = None
    if not args.local:
        result, problem = evaluate_in_sandbox(project, args.gate_point, root)
        if problem:
            print(f"error: the policies could not be evaluated: {problem}", file=sys.stderr)
            return 2
    if result is None:
        try:
            result = evaluate_locally(project, args.gate_point, root)
        except (RuntimeError, ValueError) as exc:
            print(f"error: the policies could not be evaluated: {exc}", file=sys.stderr)
            return 2
    print(report(result))
    if result.get("blocking"):
        return 1
    return 2 if result.get("errors") else 0


if __name__ == "__main__":
    sys.exit(main())
